---
- name: Generate and install device config
  hosts:
    - all
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no
  vars:
    tmp_dir: "tmp"
    conf_file: "{{ tmp_dir }}/{{ inventory_hostname }}.conf"
    connection_settings:
      host: "{{ ansible_host }}"
      user: "{{ ansible_ssh_user }}"
      passwd: "{{ ansible_ssh_pass }}"
      port: 22
      timeout: 120
  tasks:
    - name: confirm or create configs directory
      file:
        path: "{{ tmp_dir }}"
        state: directory
      run_once: yes
    - name: save device info using template
      template:
        src: template/base-settings.j2
        dest: "{{ conf_file }}"
    - name: show config changes
      debug:
        var: config_results.diff_lines
      when: config_results.diff_lines is defined
