- hosts: all
  name: install dependencies
  gather_facts: false
  roles: 
    - { role: os-packages, tags: ["infra"] }
    - { role: os-updates, tags: ["infra"] }
  
  handlers:
  - name: restart ntpd
    service: name=ntpd state=restarted