---
- name: install config onto device
  juniper_junos_config:
    provider: "{{ connection_settings }}"
    src: "{{ config_file }}"
    load: replace
    confirmed: 5
    diff: yes
    ignore_warning: yes
    comment: "playbook {{ playbook_name }}, commit confirmed"
  notify: confirm commit

- name: confirm commit
  juniper_junos_config:
    provider: "{{ connection_settings }}"
    commit: yes
    comment: "playbook {{ playbook_name }}, confirming previous commit"