- firewalld:
    port: 8080/tcp
    permanent: yes
    state: enabled
    immediate: yes
- firewalld:
    port: 6443/tcp
    permanent: yes
    state: enabled
    immediate: yes
- firewalld:
    port: 80/tcp
    permanent: yes
    state: enabled
    immediate: yes
- firewalld:
    port: 10250/udp
    permanent: yes
    state: enabled
    immediate: yes
- name: Enable firewalld
  service: name=firewalld state=started enabled=yes

- name: set IPtable rule for tcp port 6443
  command: iptables -A OUTPUT -p tcp --dport 6443 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
- name: set IPtable rule for tcp port 10250
  command: iptables -A OUTPUT -p tcp --dport 10250 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
- name: set IPtable rule for tcp port 80
  command: iptables -A OUTPUT -p tcp --dport 80 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
- name: set IPtable rule for tcp port 8080
  command: iptables -A OUTPUT -p tcp --dport 8080 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
- name: save iptables
  service: iptables-save
- name: restart iptables
  command: name=ufw state=restarted

- name: Sets enforce
  shell: setenforce 0
- name: Disable SELinux
  selinux:
    state: disabled

- name: set timezone
  shell: timedatectl set-timezone Europe/Dublin
- name: Copy over the NTP configuration
  template: src=./templates/ntp.conf dest=/etc/ntp.conf
  notify:
  - restart ntpd
  tags: ntp
- name: Make sure NTP is stopped
  service: name=ntpd state=stopped enabled=yes
  tags: ntp
- name: Sync time initialy
  shell: ntpdate 172.16.20.1
  tags: ntp
- name: Make sure NTP is started up
  service: name=ntpd state=running enabled=yes
  tags: ntp
- name: Sync hwclock
  shell: hwclock -w
  tags: ntp

- name: Update hosts file
  blockinfile:
    path: /etc/hosts
    create: yes
    block: |
      {% for item in ansible_play_batch %}
      {{ hostvars[item].ansible_ssh_host }}   {{ item }}
      {% endfor %}