- firewalld:
    port: 8080/tcp
    permanent: yes
    state: enabled
    immediate: yes
- firewalld:
    port: 6443/tcp
    permanent: yes
    state: enabled
    immediate: yes
- firewalld:
    port: 80/tcp
    permanent: yes
    state: enabled
    immediate: yes
- firewalld:
    port: 10250/udp
    permanent: yes
    state: enabled
    immediate: yes
- name: Enable firewalld
  service: name=firewalld state=started enabled=yes

- iptables_raw:
  name: allow_tcp_port_6443
  rules: '-A OUTPUT -p tcp --dport 6443 -j ACCEPT'
- iptables_raw:
  name: allow_tcp_port_10250
  rules: '-A OUTPUT -p tcp --dport 10250 -j ACCEPT'
- iptables_raw:
  name: allow_tcp_port_80
  rules: '-A OUTPUT -p tcp --dport 80 -j ACCEPT'
- iptables_raw:
  name: allow_tcp_port_8080
  rules: '-A OUTPUT -p tcp --dport 8080 -j ACCEPT'

- name: Sets enforce
  shell: setenforce 0
- name: Disable SELinux
  selinux:
    state: disabled

- name: set timezone
  shell: timedatectl set-timezone Europe/Dublin
- name: Copy over the NTP configuration
  template: src=./templates/ntp.conf dest=/etc/ntp.conf
  notify:
  - restart ntpd
  tags: ntp
- name: Make sure NTP is stopped
  service: name=ntpd state=stopped enabled=yes
  tags: ntp
- name: Sync time initialy
  shell: ntpdate 172.16.20.1
  tags: ntp
- name: Make sure NTP is started up
  service: name=ntpd state=running enabled=yes
  tags: ntp
- name: Sync hwclock
  shell: hwclock -w
  tags: ntp

- name: Update hosts file
  blockinfile:
    path: /etc/hosts
    create: yes
    block: |
      {% for item in ansible_play_batch %}
      {{ hostvars[item].ansible_ssh_host }}   {{ item }}
      {% endfor %}